Sprint 3
iHamsin/practicum-shortener-service pull request #12
Opened 2023-12-12 17:07 UTC by iHamsin

2023-12-13 17:36 UTC, arttet commented
Please add the CodeCov Coverage Report

2023-12-13 17:44 UTC, arttet requested changes
Please add more tests

2023-12-13 17:44 UTC, arttet commented on internal/repositories/interfaces.go
> +				CREATE TABLE IF NOT EXISTS  "public"."links" (
Please use migrations.

2023-12-13 17:44 UTC, arttet commented on internal/repositories/linkRepoInPGSQL.go
> +func (r *linkRepoInPGSQL) Insert(originalURL string) (string, error) {
You should provide a context here.

2023-12-13 17:44 UTC, arttet commented on internal/repositories/linkRepoInPGSQL.go
> +func (r *linkRepoInPGSQL) Insert(originalURL string) (string, error) {
```suggestion
func (r *repo) InsertUrl(originalURL string) (string, error) {
```

2023-12-18 16:03 UTC, arttet approved these changes

2023-12-18 16:03 UTC, arttet commented on internal/repositories/interfaces.go
> +//go:embed migrations/*.sql
Please move it to the `migrations` dir.

2023-12-18 16:03 UTC, arttet commented on internal/repositories/migrations/00001_init.up.sql
> +CREATE INDEX "original_link" ON "public"."links" USING btree (
Why do you use `btree` indexes?

2023-12-22 05:09 UTC, iHamsin commented on internal/repositories/migrations/00001_init.up.sql
> +CREATE INDEX "original_link" ON "public"."links" USING btree (
Unusable DB index deleted in new migration

2023-12-22 06:06 UTC, merged